apiVersion: v1
kind: Pod
metadata:
  name: gpu-benchmark-nocpu
spec:
      securityContext:
        runAsUser: 71032
        runAsGroup: 9915
        fsGroup: 9915
      containers:
      - name: gpu-benchmark
        image: pytorch/pytorch:latest
        imagePullPolicy: IfNotPresent
        command: ["python", "/sciclone/geograd/GPU_THRASH_TIMING_TEST/gpu_benchmark.py", "--cpu", "0", "--memory", "16"]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "16Gi"
          requests:
            nvidia.com/gpu: 1
            memory: "16Gi"
        volumeMounts:
        - name: sciclone-volume
          mountPath: /sciclone/
        securityContext:
          allowPrivilegeEscalation: false
      volumes:
      - name: sciclone-volume
        nfs:
          server: 128.239.59.144
          path: /sciclone/
      restartPolicy: Never
